#!/bin/sh

set -e

AUTOCONF_VERSION=2.59

PHP_VERSION="5.3.10"
PHP_URL="http://us.php.net/get/php-5.3.10.tar.bz2/from/www.php.net/mirror"

APC_VERSION="3.1.9"
APC_URL="http://pecl.php.net/get/APC-3.1.9.tgz"

SUNDOWN_VERSION="0.3.3"
SUNDOWN_URL="https://github.com/chobie/php-sundown.git"
SUNDOWN_DIR="php-sundown"

ICU_VERSION="4.4.2"
ICU_URL="http://download.icu-project.org/files/icu4c/4.4.2/icu4c-4_4_2-src.tgz"

# node_version="$1"

# if [ "$node_version" == "" ]; then
#   echo "usage: $0 VERSION"
#   exit 1
# fi

#if [ "$AWS_ID" == "" ]; then
#  echo "must set AWS_ID"
#  exit 1
#fi

#if [ "$AWS_SECRET" == "" ]; then
#  echo "must set AWS_SECRET"
#  exit 1
#fi

#if [ "$S3_BUCKET" == "" ]; then
#  echo "must set S3_BUCKET"
#  exit 1
#fi

old_pwd="$(pwd)"

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

# make a temp directory
tempdir="$( mktemp -t php_XXXX )"

echo "Temp Dir : $tempdir"

rm -rf $tempdir
mkdir -p $tempdir
cd $tempdir

echo "Download ICU ${ICU_VERSION}..."
curl -sL ${ICU_URL} -o icu-${ICU_VERSION}.tgz

echo "Extract ICU ${ICU_VERSION}..."
tar xzf icu-${ICU_VERSION}.tgz
mv icu/ icu-${ICU_VERSION}

echo "Use vulcan to build ICU for Heroku instance..."
vulcan build -v -s icu-${ICU_VERSION} -o $tempdir/icu-${ICU_VERSION}-heroku.tar.gz -p /app/vendor/php/icu -c 'cd source/ && ./runConfigureICU Linux --enable-tests=no --enable-samples=no --exec-prefix=/app/vendor/php/icu --prefix=/app/vendor/php/icu && make install'

echo "Download PHP ${PHP_VERSION}..."
curl -sL ${PHP_URL} -o php-${PHP_VERSION}.tar.bz2

echo "Extract PHP ${PHP_VERSION}..."
tar jxf php-${PHP_VERSION}.tar.bz2

echo "Extract ICU ${ICU_VERSION}-heroku..."
mkdir ./php-${PHP_VERSION}/icu
tar -xzf $tempdir/icu-${ICU_VERSION}-heroku.tar.gz -C ./php-${PHP_VERSION}/icu

echo "Download APC ${APC_VERSION}..."
curl -sL ${APC_URL} -o APC-${APC_VERSION}.tgz

echo "Extract APC ${APC_VERSION}..."
tar zxf APC-${APC_VERSION}.tgz
mv APC-${APC_VERSION}/ ./php-${PHP_VERSION}/ext/apc

echo "Download SUNDOWN ${SUNDOWN_VERSION}..."
#curl -sL ${SUNDOWN_URL} -o SUNDOWN-${SUNDOWN_VERSION}.tgz
git clone ${SUNDOWN_URL} ${SUNDOWN_DIR}
cd ${SUNDOWN_DIR}
git submodule update --init
cp sundown/src/* .
cp sundown/html/* .
cd ..


echo "Extract SUNDOWN ${SUNDOWN_VERSION}..."
#tar zxf SUNDOWN-${SUNDOWN_VERSION}.tgz
mv ${SUNDOWN_DIR} ./php-${PHP_VERSION}/ext/sundown

cd php-${PHP_VERSION}
echo "Reconfigure PHP with extra extensions..."
rm -rf ./configure

export PHP_AUTOCONF="autoconf${AUTOCONF_VERSION}"
./buildconf --force

cd ..

echo "Use vulcan to build PHP for Heroku instance..."
vulcan build -v -s php-${PHP_VERSION} -o $tempdir/php-${PHP_VERSION}-with-fpm-sundown-heroku.tar.gz -p /app/vendor/php -c 'mkdir -p /app/vendor/php/icu && cp -r icu/ /app/vendor/php && ./configure  --prefix=/app/vendor/php --without-pear --with-pdo-pgsql --with-pgsql --with-icu-dir=/app/vendor/php/icu --enable-intl --with-iconv --with-gd --with-jpeg-dir --with-png-dir --with-gif-dir --with-curl=/usr/lib --with-config-file-path=/app/vendor/php --with-openssl --enable-fpm --with-zlib --enable-mbstring --disable-debug --enable-inline-optimization --with-bz2 --enable-pcntl --enable-mbregex --with-mhash --enable-zip --with-pcre-regex --enable-apc --enable-sundown=shared && make install'

# upload to s3
#$basedir/aws/s3 put $S3_BUCKET php-5.3.9-with-fpm-heroku.tar.gz $tempdir/php-5.3.9-with-fpm-heroku.tar.gz

cd $old_pwd
